[build]
builder = "dockerfile"
dockerfile = "backend/Dockerfile"

[deploy]

[deploy.targets.backend]
directory = "backend"

[deploy.targets.backend.variables]
DATABASE_URL = "postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}"
PYTHONPATH = "/app"
PORT = "8000"
